name: sponge_client_dart
version: 1.8.0

description: Sponge client for Dart. It simplifies connecting to a remote Sponge REST API service.
author: The Sponge Team <sponge_team@softelnet.com>
homepage: https://github.com/softelnet/sponge_client_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  http: ^0.12.0+2
  synchronized: ^2.1.0
  quiver: ^2.0.3
  timezone: ^0.5.2
  intl: ^0.15.8
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.6.2
  pedantic: ^1.5.0
