name: sponge_client_dart
version: 1.14.0+1

description: Sponge client for Dart. It simplifies connecting to a remote Sponge service.
homepage: https://github.com/softelnet/sponge_client_dart

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  meta: ^1.1.8
  http: ^0.12.0+2
  synchronized: ^2.1.1
  quiver: ^2.0.5
  timezone: ^0.5.6
  intl: ^0.16.0
  equatable: ^1.0.1
  collection: ^1.14.11
  logging: ^0.11.3+2

dev_dependencies:
  test: ^1.9.4
  pedantic: ^1.9.0
