name: sponge_client_dart
version: 1.5.0

description: Sponge client for Dart
author: The Sponge Team <sponge_team@softelnet.com>
homepage: https://github.com/softelnet/sponge_client_dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  http: ^0.12.0
  synchronized: ^1.5.3
  quiver: ^2.0.0+1

dev_dependencies:
  test: ^1.5.1
  pedantic: '1.1.0'
